name: celebrazioni
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.3
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.2
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Mulish
      fonts:
        - asset: assets/fonts/MuliSemiBold.ttf
          weight: 600
